name: Desktop build - Win
on: push

jobs:
  build:
    name: Build Windows desktop app
    runs-on: ubuntu-latest
    # container:
    #   image: electronuserland/builder:wine
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Pre-install commands
        run: |
          sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine32
      - name: Install build deps
        run: |
          sudo apt install -y python make gcc libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Build app
        env:
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
        run: |
          yarn build-electron:win
        working-directory: products/jbrowse-desktop
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Copy desktop Windows build to S3
        run: |
          cd products/jbrowse-desktop/dist && zip -r "jbrowse-desktop-windows-build-test.zip" . && cd -
          aws s3 sync --delete products/jbrowse-desktop/dist s3://jbrowse.org/code/jb2/desktop-build-test
