# Upload website
on: push
name: Upload website
jobs:
  build:
    name: upload_web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: website
      - name: Build website
        run: |
          cd website/
          yarn build
          cd docs/
          make pdf # generate the pdfcombined.md, run pandoc in docker in the next step
          cp pdfcombined.md ../../
          cp titlemod.md ../../
          cp listings.tex ../../
          cd ../../
          ln -s website/docs/img
          cat <<EOF > entrypoint.sh
          #!/bin/sh -l
          /opt/texlive/texdir/bin/x86_64-linuxmusl/tlmgr install pmboxdraw
          echo "installed"
          /usr/bin/pandoc --pdf-engine /opt/texlive/texdir/bin/x86_64-linuxmusl/pdflatex --listings -H listings.tex --toc -o website/jbrowse2.pdf website/docs/titlemod.md pdfcombined.md
          EOF
          chmod +x entrypoint.sh
          cat entrypoint.sh
      - uses: docker://pandoc/latex:2.9
        with:
          entrypoint: /github/workspace/entrypoint.sh
